### PR TITLE
add .travis.yml for travis-ci

### PR DESCRIPTION
**Pull request by ua74e3dqka**
This builds i1.pdf on travis-ci.org and uploads this build artifact to
  github releases if the commit is tagged.

  # Example cli:
  $ git add . && git commit -m "my message"
  $ git tag 2018-11-26
  $ git push origin --tags
  $ git push origin master

  # Example configurations and builds
  https://travis-ci.org/ua74e3dqka/schreibe-dein-programm/builds/459634334
  https://github.com/ua74e3dqka/schreibe-dein-programm/releases/tag/2018-26-11c

  To make this work you need a travis-ci.org account which has at least
  rights to read the repo and deploy the artifact.  Then you need to define
  an environmental variable named GITHUB_API_KEY with the content of
  your OAuth key at GitHub. This prevents leaking the key to a public
  repository.

### CODE REVIEW

**Comment by mikesperber** [comment]
@ua74e3dqka Many thanks, this is fantastic!

So I now have this:

https://travis-ci.org/deinprogramm/schreibe-dein-programm

... but it seems not to be automatically building the tag that I have on github, nor pushing a release.  I did provide the OAuth. Any idea what I'm missing?  No doubt I'm being stupid about travis-ci, which I haven't used before.

**Comment by ua74e3dqka** [comment]
@mikesperber 

Looking at you travis build log (have a look at the tail of the log file) it seems that you missed to push the tags before pushing the commits themselves to github. At least this happened to me, while testing the travis cofiguration on my end (also first time using travis :-))

**Comment by mikesperber** [comment]
@ua74e3dqka I'm probably too much of a git noob, but the tag is there:

https://github.com/deinprogramm/schreibe-dein-programm/tree/2018-12-02

Could it be something with the travis-ci settings? But I don't see anything relevant ...

**Comment by ua74e3dqka** [comment]
@mikesperber Did you try to re-tag the current commit and push it again? Your build log seems to communicate exactly this.

**Comment by mikesperber** [comment]
@ua74e3dqka Ah, that's possible.

**Comment by mikesperber** [comment]
@ua74e3dqka Just tagged today's work and pushed, but still doesn't show up in travis's "Branches" list.

**Comment by ua74e3dqka** [comment]
I am pretty sure the current build is going to be uploaded to gh releases. Do you see the difference in the travis-ci UI?

image

**Comment by ua74e3dqka** [comment]
We did it, didn't we 👍

**Comment by mikesperber** [comment]
@ua74e3dqka Indeed - many thanks for your patience!

**Pull request merged**
